services:
  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    env_file:
      - .env
    ports:
      - 1026:1025
      - 8026:8025
    volumes:
      - ../../docker-data/mailhog:/maildir
